language: c
sudo: required
branches:
  only:
    - "master"
    - "develop"

before_install:
  - echo "deb   http://apt.openlighting.org/ubuntu  trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-key update
  - sudo apt-get -qq update
#  - sudo apt-get install -y ola
  - sudo apt-get -o Debug::pkgProblemResolver=true -o Debug::pkgDPkgPM=true -o Debug::RunScripts install -y --allow-unauthenticated ola
#  - sudo find / -name DmxBuffer.h 2> /dev/null
  - ls -l /usr/local/include
  - ls -l /usr/local/include/ola
  - ls -l /usr/local/include/olad

  #- sudo apt-get install -y libcppunit-dev
  #- sudo apt-get install -y libprotobuf-dev
  #- sudo apt-get install -y libprotoc-dev
  #- sudo apt-get install -y protobuf-compiler
  #- git clone https://github.com/OpenLightingProject/ola.git ola
  #- cd ola
  #- autoreconf -i
  #- ./configure
  #- make
  #- make check
  #- sudo make install
  #- sudo ldconfig
  #- cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && ctest -V
