language: c
sudo: required
branches:
  only:
    - "master"
    - "develop"

before_install:
  - sudo add-apt-repository -y ppa:voltvisionfrenchy/ola
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends libola-dev
  - sudo apt-get install -y --no-install-recommends libncurses5-dev
  - sudo apt-get install -y --no-install-recommends systemd
  - sudo apt-get install -y --no-install-recommends libsystemd-daemon-dev
  - sudo apt-get install -y --no-install-recommends libsystemd-daemon0


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - sudo make install
  - make PCA9685test
  - ctest -V
  - make examples
  - cd examples/olaclient
  - sudo make install
  - sudo systemctl daemon-reload
  - sudo systemctl list-units --all
  - sudo systemctl start olac.service
  - sudo systemctl status olac.service
  - cat /var/log/olac.log
  - sudo cat /var/log/syslog
