language: c
sudo: required
branches:
  only:
    - "master"
    - "develop"

before_install:
  - sudo add-apt-repository -y ppa:voltvisionfrenchy/ola
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends libola-dev
  - sudo apt-get install -y --no-install-recommends libncurses5-dev


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - sudo make install
  - make PCA9685test
  - ctest -V
  - make examples
  - cd examples/olaclient
  - sudo make install
  - sudo find / -name init-d-script -print
  - sudo /etc/init.d/olac start
  - cat /var/log/olac.log
