language: c
sudo: required
branches:
  only:
    - "master"
    - "develop"

before_install:
  - sudo add-apt-repository -y ppa:voltvisionfrenchy/ola
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends libola-dev
  - sudo apt-get install -y --no-install-recommends libncurses5-dev
  - sudo apt-get install -y --no-install-recommends systemd


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - sudo make install
# move this to CMakeLists.txt for libPCA9685:
  - sudo ldconfig

  - make PCA9685test
  - ctest -V

  - make examples
  - cd examples/olaclient
  - ls -l /bin/systemctl
# this contains systemctl calls that "pass":
  - sudo make install
  - ls -l /etc/systemd/system/
  - ls -l /etc/systemd/system/multi-user.target.wants/
# but the log should show an open() failure:
  - cat /var/log/olac.log
