language: c
sudo: required
branches:
  only:
    - "master"
    - "develop"

before_install:
  - echo "deb   http://apt.openlighting.org/ubuntu  trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-key update
  - sudo apt-get -qq update
  - sudo apt-get install -y ola

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && ctest -V
