language: c
sudo: required
branches:
  only:
    - "master"
    - "develop"

before_install:
  - sudo add-apt-repository -y ppa:voltvisionfrenchy/ola
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends libola-dev
  - sudo apt-get install -y --no-install-recommends libncurses5-dev
  - sudo apt-get install -y --no-install-recommends libasound2-dev
  - sudo apt-get install -y --no-install-recommends libfftw3-3
  - sudo apt-get install -y --no-install-recommends systemd

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - sudo make install

  - make PCA9685test
  - ctest -V

  - make examples
  - cd examples/olaclient
# this contains systemctl calls that "pass":
  - sudo make install
# but the log should show an open() failure:
  - cat /var/log/olac.log
  - cd ../..

  - cd examples/audio
  - sudo make install
  - cat /var/log/vupeak.log
  - cd ../..
