language: c
sudo: required
branches:
  only:
    - "master"
    - "develop"
    - "ola"
    - "ola-fix-travis"

before_install:
  - sudo apt-get install -y libola-dev


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && ctest -V
